data_list = [['2018^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2018/seasontype/2'],
             ['2018^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2018/seasontype/2'],
             ['2018^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2018/seasontype/2'],
             ['2017^^Golden State^^2', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2017/seasontype/2'],
             ['2017^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2017/seasontype/2'],
             ['2017^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2017/seasontype/2'],
             ['2017^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2017/seasontype/2'],
             ['2016^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2016/seasontype/2'],
             ['2016^^Charlotte^^2', 'http://www.espn.com/nba/team/schedule/_/name/cha/year/2016/seasontype/2'],
             ['2016^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2016/seasontype/2'],
             ['2016^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2016/seasontype/2'],
             ['2016^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2016/seasontype/2'],
             ['2016^^Indiana^^2', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2016/seasontype/2'],
             ['2016^^LA Lakers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2016/seasontype/2'],
             ['2016^^Philadelphia^^2', 'http://www.espn.com/nba/team/schedule/_/name/phi/year/2016/seasontype/2'],
             ['2015^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2015/seasontype/2'],
             ['2015^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2015/seasontype/2'],
             ['2015^^Dallas^^2', 'http://www.espn.com/nba/team/schedule/_/name/dal/year/2015/seasontype/2'],
             ['2015^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2015/seasontype/2'],
             ['2015^^LA Lakers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2015/seasontype/2'],
             ['2013^^Dallas^^2', 'http://www.espn.com/nba/team/schedule/_/name/dal/year/2013/seasontype/2'],
             ['2013^^Portland^^2', 'http://www.espn.com/nba/team/schedule/_/name/por/year/2013/seasontype/2'],
             ['2013^^New Orleans^^2', 'http://www.espn.com/nba/team/schedule/_/name/no/year/2013/seasontype/2'],
             ['2013^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2013/seasontype/2'],
             ['2013^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2013/seasontype/2'],
             ['2013^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2013/seasontype/2'],
             ['2013^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2013/seasontype/2'],
             ['2013^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2013/seasontype/2'],
             ['2013^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2013/seasontype/2'],
             ['2013^^Miami^^3', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2013/seasontype/3'],
             ['2013^^Indiana^^3', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2013/seasontype/3'],
             ['2012^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2012/seasontype/2'],
             ['2012^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2012/seasontype/2'],
             ['2012^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2012/seasontype/2'],
             ['2012^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2012/seasontype/2'],
             ['2012^^Oklahoma City^^3', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2012/seasontype/3'],
             ['2012^^Miami^^3', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2012/seasontype/3'],
             ['2011^^LA Lakers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2011/seasontype/2'],
             ['2011^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2011/seasontype/2'],
             ['2011^^New Orleans^^2', 'http://www.espn.com/nba/team/schedule/_/name/no/year/2011/seasontype/2'],
             ['2011^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2011/seasontype/2'],
             ['2011^^Oklahoma City^^3', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2011/seasontype/3'],
             ['2011^^Memphis^^3', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2011/seasontype/3'],
             ['2010^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2010/seasontype/2'],
             ['2010^^Utah^^2', 'http://www.espn.com/nba/team/schedule/_/name/utah/year/2010/seasontype/2'],
             ['2010^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2010/seasontype/2'],
             ['2010^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2010/seasontype/2'],
             ['2010^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2010/seasontype/2'],
             ['2009^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2009/seasontype/2'],
             ['2009^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2009/seasontype/2'],
             ['2009^^Indiana^^2', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2009/seasontype/2'],
             ['2009^^Houston^^2', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2009/seasontype/2'],
             ['2009^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2009/seasontype/2'],
             ['2009^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2009/seasontype/2'],
             ['2009^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2009/seasontype/2'],
             ['2009^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2009/seasontype/2'],
             ['2009^^Charlotte^^2', 'http://www.espn.com/nba/team/schedule/_/name/cha/year/2009/seasontype/2'],
             ['2009^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2009/seasontype/2'],
             ['2009^^Oklahoma City^^2', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2009/seasontype/2'],
             ['2009^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2009/seasontype/2'],
             ['2008^^Golden State^^2', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2008/seasontype/2'],
             ['2008^^LA Lakers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2008/seasontype/2'],
             ['2008^^Utah^^2', 'http://www.espn.com/nba/team/schedule/_/name/utah/year/2008/seasontype/2'],
             ['2008^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2008/seasontype/2'],
             ['2008^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2008/seasontype/2'],
             ['2008^^Orlando^^2', 'http://www.espn.com/nba/team/schedule/_/name/orl/year/2008/seasontype/2'],
             ['2008^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2008/seasontype/2'],
             ['2008^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2008/seasontype/2'],
             ['2008^^Houston^^2', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2008/seasontype/2'],
             ['2008^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2008/seasontype/2'],
             ['2008^^Atlanta^^2', 'http://www.espn.com/nba/team/schedule/_/name/atl/year/2008/seasontype/2'],
             ['2008^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2008/seasontype/2'],
             ['2008^^Philadelphia^^2', 'http://www.espn.com/nba/team/schedule/_/name/phi/year/2008/seasontype/2'],
             ['2008^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2008/seasontype/2'],
             ['2008^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2008/seasontype/2'],
             ['2008^^New York^^2', 'http://www.espn.com/nba/team/schedule/_/name/ny/year/2008/seasontype/2'],
             ['2008^^Chicago^^2', 'http://www.espn.com/nba/team/schedule/_/name/chi/year/2008/seasontype/2'],
             ['2008^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2008/seasontype/2'],
             ['2008^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2008/seasontype/2'],
             ['2008^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2008/seasontype/2'],
             ['2008^^Seattle^^2', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2008/seasontype/2'],
             ['2008^^LA Lakers^^3', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2008/seasontype/3'],
             ['2008^^San Antonio^^3', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2008/seasontype/3'],
             ['2008^^Houston^^3', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2008/seasontype/3'],
             ['2007^^Golden State^^3', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2007/seasontype/3'],
             ['2007^^San Antonio^^3', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2007/seasontype/3'],
             ['2007^^Houston^^3', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2007/seasontype/3'],
             ['2006^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2006/seasontype/2'],
             ['2006^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2006/seasontype/2'],
             ['2006^^Dallas^^2', 'http://www.espn.com/nba/team/schedule/_/name/dal/year/2006/seasontype/2'],
             ['2006^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2006/seasontype/2'],
             ['2006^^Seattle^^2', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2006/seasontype/2'],
             ['2006^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2006/seasontype/2'],
             ['2006^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2006/seasontype/2'],
             ['2006^^San Antonio^^2', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2006/seasontype/2'],
             ['2006^^Philadelphia^^2', 'http://www.espn.com/nba/team/schedule/_/name/phi/year/2006/seasontype/2'],
             ['2006^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2006/seasontype/2'],
             ['2006^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2006/seasontype/2'],
             ['2006^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2006/seasontype/2'],
             ['2006^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2006/seasontype/2'],
             ['2006^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2006/seasontype/2'],
             ['2006^^Golden State^^2', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2006/seasontype/2'],
             ['2006^^Atlanta^^2', 'http://www.espn.com/nba/team/schedule/_/name/atl/year/2006/seasontype/2'],
             ['2006^^Orlando^^2', 'http://www.espn.com/nba/team/schedule/_/name/orl/year/2006/seasontype/2'],
             ['2006^^New Jersey^^2', 'http://www.espn.com/nba/team/schedule/_/name/bkn/year/2006/seasontype/2'],
             ['2006^^Chicago^^2', 'http://www.espn.com/nba/team/schedule/_/name/chi/year/2006/seasontype/2'],
             ['2006^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2006/seasontype/2'],
             ['2006^^Indiana^^2', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2006/seasontype/2'],
             ['2006^^Charlotte^^2', 'http://www.espn.com/nba/team/schedule/_/name/cha/year/2006/seasontype/2'],
             ['2006^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2006/seasontype/2'],
             ['2006^^Utah^^2', 'http://www.espn.com/nba/team/schedule/_/name/utah/year/2006/seasontype/2'],
             ['2006^^Houston^^2', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2006/seasontype/2'],
             ['2006^^New York^^2', 'http://www.espn.com/nba/team/schedule/_/name/ny/year/2006/seasontype/2'],
             ['2006^^Portland^^2', 'http://www.espn.com/nba/team/schedule/_/name/por/year/2006/seasontype/2'],
             ['2006^^Milwaukee^^3', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2006/seasontype/3'],
             ['2006^^Detroit^^3', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2006/seasontype/3'],
             ['2005^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2005/seasontype/2'],
             ['2005^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2005/seasontype/2'],
             ['2005^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2005/seasontype/2'],
             ['2005^^Dallas^^2', 'http://www.espn.com/nba/team/schedule/_/name/dal/year/2005/seasontype/2'],
             ['2005^^Seattle^^2', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2005/seasontype/2'],
             ['2005^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2005/seasontype/2'],
             ['2005^^Toronto^^2', 'http://www.espn.com/nba/team/schedule/_/name/tor/year/2005/seasontype/2'],
             ['2005^^San Antonio^^2', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2005/seasontype/2'],
             ['2005^^Washington^^2', 'http://www.espn.com/nba/team/schedule/_/name/wsh/year/2005/seasontype/2'],
             ['2005^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2005/seasontype/2'],
             ['2005^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2005/seasontype/2'],
             ['2005^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2005/seasontype/2'],
             ['2005^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2005/seasontype/2'],
             ['2005^^Golden State^^2', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2005/seasontype/2'],
             ['2005^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2005/seasontype/2'],
             ['2005^^Indiana^^2', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2005/seasontype/2'],
             ['2005^^Orlando^^2', 'http://www.espn.com/nba/team/schedule/_/name/orl/year/2005/seasontype/2'],
             ['2005^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2005/seasontype/2'],
             ['2005^^Philadelphia^^2', 'http://www.espn.com/nba/team/schedule/_/name/phi/year/2005/seasontype/2'],
             ['2005^^Utah^^2', 'http://www.espn.com/nba/team/schedule/_/name/utah/year/2005/seasontype/2'],
             ['2005^^Portland^^2', 'http://www.espn.com/nba/team/schedule/_/name/por/year/2005/seasontype/2'],
             ['2005^^New Jersey^^2', 'http://www.espn.com/nba/team/schedule/_/name/bkn/year/2005/seasontype/2'],
             ['2005^^Charlotte^^2', 'http://www.espn.com/nba/team/schedule/_/name/cha/year/2005/seasontype/2'],
             ['2005^^Atlanta^^2', 'http://www.espn.com/nba/team/schedule/_/name/atl/year/2005/seasontype/2'],
             ['2005^^New Orleans^^2', 'http://www.espn.com/nba/team/schedule/_/name/no/year/2005/seasontype/2'],
             ['2005^^Sacramento^^3', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2005/seasontype/3'],
             ['2005^^Seattle^^3', 'http://www.espn.com/nba/team/schedule/_/name/okc/year/2005/seasontype/3'],
             ['2005^^Washington^^3', 'http://www.espn.com/nba/team/schedule/_/name/wsh/year/2005/seasontype/3'],
             ['2005^^Detroit^^3', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2005/seasontype/3'],
             ['2005^^Indiana^^3', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2005/seasontype/3'],
             ['2004^^LA Lakers^^3', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2004/seasontype/3'],
             ['2004^^Minnesota^^3', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2004/seasontype/3'],
             ['2004^^San Antonio^^3', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2004/seasontype/3'],
             ['2004^^Indiana^^3', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2004/seasontype/3'],
             ['2004^^Denver^^3', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2004/seasontype/3'],
             ['2003^^Milwaukee^^2', 'http://www.espn.com/nba/team/schedule/_/name/mil/year/2003/seasontype/2'],
             ['2003^^LA Lakers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lal/year/2003/seasontype/2'],
             ['2003^^Minnesota^^2', 'http://www.espn.com/nba/team/schedule/_/name/min/year/2003/seasontype/2'],
             ['2003^^Golden State^^2', 'http://www.espn.com/nba/team/schedule/_/name/gs/year/2003/seasontype/2'],
             ['2003^^Sacramento^^2', 'http://www.espn.com/nba/team/schedule/_/name/sac/year/2003/seasontype/2'],
             ['2003^^Orlando^^2', 'http://www.espn.com/nba/team/schedule/_/name/orl/year/2003/seasontype/2'],
             ['2003^^Detroit^^2', 'http://www.espn.com/nba/team/schedule/_/name/det/year/2003/seasontype/2'],
             ['2003^^Portland^^2', 'http://www.espn.com/nba/team/schedule/_/name/por/year/2003/seasontype/2'],
             ['2003^^San Antonio^^2', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2003/seasontype/2'],
             ['2003^^Philadelphia^^2', 'http://www.espn.com/nba/team/schedule/_/name/phi/year/2003/seasontype/2'],
             ['2003^^Indiana^^2', 'http://www.espn.com/nba/team/schedule/_/name/ind/year/2003/seasontype/2'],
             ['2003^^Washington^^2', 'http://www.espn.com/nba/team/schedule/_/name/wsh/year/2003/seasontype/2'],
             ['2003^^Memphis^^2', 'http://www.espn.com/nba/team/schedule/_/name/mem/year/2003/seasontype/2'],
             ['2003^^Phoenix^^2', 'http://www.espn.com/nba/team/schedule/_/name/phx/year/2003/seasontype/2'],
             ['2003^^New Jersey^^2', 'http://www.espn.com/nba/team/schedule/_/name/bkn/year/2003/seasontype/2'],
             ['2003^^New Orleans^^2', 'http://www.espn.com/nba/team/schedule/_/name/no/year/2003/seasontype/2'],
             ['2003^^Utah^^2', 'http://www.espn.com/nba/team/schedule/_/name/utah/year/2003/seasontype/2'],
             ['2003^^Houston^^2', 'http://www.espn.com/nba/team/schedule/_/name/hou/year/2003/seasontype/2'],
             ['2003^^Boston^^2', 'http://www.espn.com/nba/team/schedule/_/name/bos/year/2003/seasontype/2'],
             ['2003^^LA Clippers^^2', 'http://www.espn.com/nba/team/schedule/_/name/lac/year/2003/seasontype/2'],
             ['2003^^Chicago^^2', 'http://www.espn.com/nba/team/schedule/_/name/chi/year/2003/seasontype/2'],
             ['2003^^Miami^^2', 'http://www.espn.com/nba/team/schedule/_/name/mia/year/2003/seasontype/2'],
             ['2003^^Cleveland^^2', 'http://www.espn.com/nba/team/schedule/_/name/cle/year/2003/seasontype/2'],
             ['2003^^Denver^^2', 'http://www.espn.com/nba/team/schedule/_/name/den/year/2003/seasontype/2'],
             ['2003^^San Antonio^^3', 'http://www.espn.com/nba/team/schedule/_/name/sa/year/2003/seasontype/3'],
             ['2003^^New Jersey^^3', 'http://www.espn.com/nba/team/schedule/_/name/bkn/year/2003/seasontype/3']]
