# -*- coding:utf-8 -*-
import re


players = {
    # 公牛
    'Jimmy Butler'            : '吉米-巴特勒',
    'Isaiah Canaan'           : '以赛亚·坎南',
    'Michael Carter-Williams' : '迈克尔-卡特-威廉姆斯',
    'Cristiano Felicio'       : '克里斯蒂亚诺-费利西奥',
    'Taj Gibson'              : '泰-吉布森',
    'Jerian Grant'            : '杰里安-格兰特',
    'R.J. Hunter'             : 'RJ-亨特',
    'Robin Lopez'             : '罗宾-洛佩斯',
    'Doug McDermott'          : '道格-迈克德莫特',
    'Nikola Mirotic'          : '尼古拉-米罗蒂奇',
    'Bobby Portis'            : '鲍比-波蒂斯',
    'Rajon Rondo'             : '拉简-朗多',
    'Denzel Valentine'        : '丹泽尔-瓦伦蒂内',
    'Dwyane Wade'             : '	德维恩-韦德',
    'Paul Zipser'             : '保罗-齐普泽',

    # 布鲁克林篮网队
    'Anthony Bennett'         : '安东尼-本内特',
    'Bojan Bogdanovic'        : '博扬-博格达诺维奇',
    'Trevor Booker'           : '特雷沃-布克',
    'Randy Foye'              : '兰迪·弗耶',
    'Justin Hamilton'         : '贾斯汀-汉密尔顿',
    'Joe Harris'              : '乔-哈里斯',
    'Rondae Hollis-Jefferson' : '朗戴-霍利斯-杰弗森',
    'Sean Kilpatrick'         : '肖恩-基尔帕特里克',
    'Caris LeVert'            : '卡里斯·勒夫特',
    'Jeremy Lin'              : '林书豪',
    'Brook Lopez'             : '布鲁克-洛佩斯',
    'Chris McCullough'        : '克里斯-麦考伦',
    'Luis Scola'              : '路易斯-斯科拉',
    'Greivis Vasquez'         : '格雷维斯-瓦斯奎兹',
    'Isaiah Whitehead'        : '伊塞亚-怀特海德',

    # 亚特兰大老鹰
    'Kent Bazemore'           : '肯特-贝兹莫尔',
    'DeAndre Bembry'          : 'DeAndre-本布里',
    'Malcolm Delaney'         : '马尔科姆-德莱尼',
    'Tim Hardaway Jr.'        : '蒂姆-哈达威二世',
    'Dwight Howard'           : '德怀特-霍华德',
    'Kris Humphries'          : '克里斯-亨弗里斯',
    'Ryan Kelly'              : '莱恩-凯利',
    'Kyle Korver'             : '凯尔-科沃尔',
    'Paul Millsap'            : '保罗-米尔萨普',
    'Mike Muscala'            : '迈克-穆斯卡拉',
    'Taurean Prince'          : '塔乌里恩-普林斯',
    'Dennis Schroder'         : '德尼斯-施罗德',
    'Mike Scott'              : '迈克-斯科特',
    'Thabo Sefolosha'         : '萨波-塞弗罗萨',
    'Tiago Splitter'          : '提亚哥-斯普里特',

    # 丹佛掘金
    'Darrell Arthur'          : '达雷尔-亚瑟',
    'Will Barton'             : '威尔-巴顿',
    'Malik Beasley'           : '马里克-比斯利',
    'Wilson Chandler'         : '威尔森-钱德勒',
    'Kenneth Faried'          : '肯尼思-法里德',
    'Danilo Gallinari'        : '达尼罗-加里纳利',
    'Gary Harris'             : '加里-哈里斯',
    'Juancho Hernangomez'     : '胡安-埃尔南戈麦斯',
    'Nikola Jokic'            : '尼科拉-约季奇',
    'Mike Miller'             : '迈克-米勒',
    'Emmanuel Mudiay'         : '伊曼纽尔-	穆迪埃',
    'Jamal Murray'            : '贾马尔-穆雷',
    'Jameer Nelson'           : '贾米尔-尼尔森',
    'Jusuf Nurkic'            : '尤素福-努尔契奇',
    'Jarnell Stokes'          : '贾内尔-斯托克斯',

    # 金州勇士
    'Ian Clark'               : '伊恩-克拉克	',
    'Stephen Curry'           : '斯蒂芬-库里',
    'Kevin Durant'            : '凯文-杜兰特',
    'Draymond Green'          : '德雷蒙德-格林',
    'Andre Iguodala'          : '安德鲁-伊格达拉',
    'Damian Jones'            : '达米安-琼斯',
    'Shaun Livingston'        : '肖恩-利文斯顿',
    'Kevon Looney'            : '凯文-鲁尼',
    'James Michael McAdoo'    : '詹姆斯-迈克尔-麦卡杜',
    'Patrick McCaw'           : '帕特里克-麦考',
    'JaVale McGee'            : '贾维尔-麦基',
    'Zaza Pachulia'           : '扎扎-帕楚里亚',
    'Klay Thompson'           : '克莱-汤普森',
    'Anderson Varejao'        : '安德森-瓦莱乔',
    'David West'              : '大卫-韦斯特',

    # 达拉斯小牛
    'Quincy Acy'              : '昆西-埃希',
    'Justin Anderson'         : '贾斯汀-安德森',
    'J.J. Barea'              : 'J.J.-巴里亚',
    'Harrison Barnes'         : '哈里森-巴恩斯',
    'Andrew Bogut'            : '安德鲁-博古特',
    'Nicolas Brussino'        : '尼古拉斯-布鲁西诺',
    'Seth Curry'              : '賽斯-库里',
    'Dorian Finney-Smith'     : '多里安-芬尼-史密斯',
    'A.J. Hammons'            : 'AJ-哈蒙斯',
    'Devin Harris'            : '德文-哈里斯',
    'Wesley Matthews'         : '韦斯利-马休斯',
    'Salah Mejri'             : '萨拉-梅吉里',
    'Dirk Nowitzki'           : '德克-诺维茨基',
    'Dwight Powell'           : '德怀特-鲍威尔',
    'Deron Williams'          : '德隆-威廉姆斯',

    # 克利夫兰骑士
    'Chris Andersen'          : '克里斯-安德森',
    'Mike Dunleavy'           : '迈克-邓利维',
    'Kay Felder'              : '凯-菲尔德',
    'Channing Frye'           : '钱宁-弗莱',
    'Kyrie Irving'            : '凯尔-欧文',
    'LeBron James'            : '勒布朗-詹姆斯',
    'Richard Jefferson'       : '理查德-杰弗森',
    'James Jones'             : '詹姆斯-琼斯',
    'DeAndre Liggins'         : '德安德烈-	利金斯',
    'Kevin Love'              : '凯文-乐福',
    'Jordan McRae'            : '乔丹-麦克雷',
    'Iman Shumpert'           : '伊曼-香珀特',
    'J.R. Smith'              : 'JR-史密斯',
    'Tristan Thompson'        : '特里斯坦-汤普森',
    'Mo Williams'             : '莫-威廉姆斯',

    # 波士顿凯尔特人

    'Avery Bradley'           : '埃弗里-布拉德利',
    'Jaylen Brown'            : '杰林-布朗',
    'Jae Crowder'             : '贾伊-克劳德',
    'Gerald Green'            : '杰拉德-格林',
    'Al Horford'              : '艾尔-霍福德',
    'Demetrius Jackson'       : '德米特里厄斯-杰克逊',
    'Jonas Jerebko'           : '乔纳斯-杰雷布科',
    'Amir Johnson'            : '阿米尔-约翰逊',
    'Jordan Mickey'           : '乔丹-米奇',
    'Kelly Olynyk'            : '凯利-奥利尼克',
    'Terry Rozier'            : '特里-洛奇尔',
    'Marcus Smart'            : '马库斯-斯玛特',
    'Isaiah Thomas'           : '以赛亚-托马斯',
    'James Young'             : '詹姆斯-杨',
    'Tyler Zeller'            : '泰勒-泽勒',

    # 夏洛特黄蜂
    'Nicolas Batum'           : '尼古拉斯-巴图姆',
    'Marco Belinelli'         : '马可-贝里内利',
    'Treveon Graham'          : '特雷维安-格拉汉姆',
    'Aaron Harrison'          : '阿隆-哈里森',
    'Spencer Hawes'           : '斯宾塞-霍伊斯',
    'Roy Hibbert'             : '罗伊-希伯特',
    'Frank Kaminsky III'      : '弗兰克-卡明斯基',
    'Michael Kidd-Gilchrist'  : '迈克尔-基德-基尔克里斯特',
    'Jeremy Lamb'             : '兰杰罗米-姆',
    'Brian Roberts'           : '布莱恩-罗伯茨',
    'Ramon Sessions'          : '雷蒙-塞申斯',
    'Kemba Walker'            : '肯巴-沃克',
    'Marvin Williams'         : '马尔文-威廉姆斯',
    'Christian Wood'          : '克里斯蒂安-伍德',
    'Cody Zeller'             : '科迪-泽勒',

    # 明尼苏达森林狼
    'Cole Aldrich'            : '科尔-阿尔德里奇',
    'Nemanja Bjelica'         : '内马尼亚-	别利察',
    'Gorgui Dieng'            : '格基-迪恩',
    'Kris Dunn'               : '克里斯-邓恩',
    'Jordan Hill'             : '乔丹-希尔',
    'Tyus Jones'              : '特尤斯-琼斯',
    'Zach LaVine'             : '扎克-拉文',
    'John Lucas III'          : '约翰-卢卡斯三世',
    'Shabazz Muhammad'        : '沙巴兹-穆罕默德',
    'Adreian Payne'           : '艾德里安-佩恩',
    'Nikola Pekovic'          : '尼克拉-佩科维奇',
    'Ricky Rubio'             : '里基-卢比奥',
    'Brandon Rush'            : '布兰登-拉什',
    'Karl-Anthony Towns'      : '卡尔-安东尼-唐斯',
    'Andrew Wiggins'          : '安德鲁-维金斯',

    # 洛杉矶快船

    'Alan Anderson'           : '阿兰-安德森',
    'Brandon Bass'            : '布兰登-巴斯',
    'Jamal Crawford'          : '贾马尔-克劳福德',
    'Raymond Felton'          : '雷蒙德-菲尔顿',
    'Blake Griffin'           : '布莱克-格里芬',
    'Brice Johnson'           : '布里斯-约翰逊',
    'Wesley Johnson'          : '韦斯利-约翰逊',
    'DeAndre Jordan'          : '德安德烈-乔丹',
    'Luc Richard Mbah a Moute': '卢克-巴莫特',
    'Chris Paul'              : '克里斯-保罗',
    'Paul Pierce'             : '保罗-皮尔斯',
    'J.J. Redick'             : 'JJ-雷迪克',
    'Austin Rivers'           : '奥斯汀-里弗斯',
    'Marreese Speights'       : '马利斯-斯贝茨',
    'Diamond Stone'           : '戴蒙德-斯通',
    'luc mbah a moute'        : '卢克-理查德-巴莫特',

    # 底特律活塞
    'Aron Baynes'             : '阿隆-贝恩斯',
    'Reggie Bullock'          : '雷吉-布洛克',
    'Kentavious Caldwell-Pope': '肯塔维奥斯-考德威尔-波普',
    'Andre Drummond'          : '安德鲁-德拉蒙德',
    'Henry Ellenson'          : '亨利-埃伦森',
    'Michael Gbinije'         : '迈克尔-本尼',
    'Tobias Harris'           : '托拜厄斯-哈里斯',
    'Darrun Hilliard'         : '达伦-希尔拉德',
    'Reggie Jackson'          : '雷吉-杰克逊',
    'Stanley Johnson'         : '斯坦利-约翰逊',
    'Jon Leuer'               : '乔恩-洛伊尔',
    'Boban Marjanovic'        : '鲍班-马亚诺维奇',
    'Marcus Morris'           : '马库斯-莫里斯',
    'Ish Smith'               : '伊斯-史密斯',
    'Beno Udrih'              : '本诺-尤德里',

    # 纽约尼克斯
    'Carmelo Anthony'         : '卡梅隆-安东尼',
    'Ron Baker'               : '罗恩-贝克',
    'Willy Hernangomez'       : 'Willy-埃尔南戈麦斯',
    'Justin Holiday'          : '贾斯汀-霍利迪',
    'Brandon Jennings'        : '布兰登-詹宁斯',
    'Mindaugas Kuzminskas'    : '明道加斯-库兹明斯卡斯',
    'Courtney Lee'            : '康特尼-李',
    'Maurice Daly Ndour'      : '莫里斯-恩多尔',
    'Joakim Noah'             : '乔金-诺阿',
    'Kyle O\'Quinn'           : '凯尔-奎恩, ',
    'Marshall Plumlee'        : '马歇尔-普拉姆利',
    'Kristaps Porzingis'      : '克里斯塔普斯-波尔津吉斯',
    'Derrick Rose'            : '德里克-罗斯',
    'Lance Thomas'            : '兰斯-托马斯',
    'Sasha Vujacic'           : '萨沙-武贾西奇',

    # 迈阿密热火

    'Luke Babbitt'            : '卢克-巴比特',
    'Chris Bosh'              : '克里斯-波什',
    'Goran Dragic'            : '戈兰-德拉季奇',
    'Wayne Ellington'         : '维恩-艾灵顿',
    'Udonis Haslem'           : '犹多尼斯-哈斯勒姆',
    'James Johnson'           : '詹姆斯-约翰逊',
    'Tyler Johnson'           : '泰勒-约翰逊',
    'Rodney McGruder'         : '罗德尼-迈克格拉德',
    'Josh McRoberts'          : '约什-麦克罗伯茨',
    'Willie Reed'             : '威利-里德',
    'Josh Richardson'         : '约什-理查德森',
    'Dion Waiters'            : '迪昂-维特斯',
    'Hassan Whiteside'        : '哈桑-怀特塞德',
    'Derrick Williams'        : '德里克-威廉姆斯',
    'Justise Winslow'         : '贾斯蒂斯-	温斯洛',

    # 俄拉克荷妈雷霆

    'Alex Abrines'            : '阿莱克斯-亚历克斯-艾布里恩',
    'Steven Adams'            : '斯蒂文-亚当斯',
    'Semaj Christon'          : '赛马耶-克里斯顿',
    'Nick Collison'           : '尼克-科里森',
    'Jerami Grant'            : '杰拉米-格兰特',
    'Josh Huestis'            : '约什-胡斯蒂斯',
    'Enes Kanter'             : '伊内斯-坎特',
    'Joffrey Lauvergne'       : '乔弗里-洛韦尔',
    'Anthony Morrow'          : '安东尼-莫罗',
    'Victor Oladipo'          : '维克托-奥拉迪普',
    'Cameron Payne'           : '卡梅隆-佩恩',
    'Andre Roberson'          : '安德鲁-罗伯森',
    'Domantas Sabonis'        : '德曼塔斯-萨博尼斯',
    'Kyle Singler'            : '凯尔-辛格勒',
    'Russell Westbrook'       : '拉塞尔-威斯布鲁克',

    # 洛杉矶湖人
    'Tarik Black'             : '塔里克-布莱克',
    'Jose Calderon'           : '何塞-卡尔德隆',
    'Jordan Clarkson'         : '乔丹-克拉克森',
    'Luol Deng'               : '罗尔-邓',
    'Marcelo Huertas'         : '马塞洛-胡尔塔斯',
    'Brandon Ingram'          : '布兰登-英格拉姆',
    'Timofey Mozgov'          : '提莫菲-莫兹戈夫',
    'Larry Nance Jr.'         : '拉里-南斯二世',
    'Julius Randle'           : '朱利叶斯-兰德尔',
    'Thomas Robinson'         : '托马斯-罗宾逊',
    'D\'Angelo Russell'       : '德安格罗-拉塞尔',
    'Louis Williams'          : '路-威廉姆斯',
    'Metta World Peace'       : '慈-世平',
    'Nick Young'              : '尼克-杨',
    'Ivica Zubac'             : '伊维察-祖巴茨',

    # 孟菲斯灰熊
    'Tony Allen'              : '托尼-	艾伦',
    'Wade Baldwin IV'         : '韦德-鲍德温',
    'Vince Carter'            : '文斯-卡特',
    'Mike Conley'             : '迈克-康利',
    'Troy Daniels'            : '特洛伊-丹尼尔斯',
    'Deyonta Davis'           : '德永塔-戴维斯',
    'James Ennis'             : '詹姆斯-恩尼斯',
    'Marc Gasol'              : '马克-加索尔',
    'JaMychal Green'          : '杰麦世尔-格林',
    'Andrew Harrison'         : '安德鲁-哈里森',
    'Jarell Martin'           : '贾雷尔-马丁',
    'Chandler Parsons'        : '钱德勒-帕森斯',
    'Zach Randolph'           : '扎克-兰多夫',
    'Troy Williams'           : '特洛伊-威廉姆斯',
    'Brandan Wright'          : '布兰登-怀特',

    # 印第安纳步行者
    'Lavoy Allen'             : '拉沃伊-艾伦',
    'Aaron Brooks'            : '阿隆-布鲁克斯',
    'Rakeem Christmas'        : '拉金-克里斯特玛斯',
    'Monta Ellis'             : '蒙塔-埃利斯',
    'Paul George'             : '保罗-乔治',
    'Al Jefferson'            : '艾尔-杰弗森',
    'C.J. Miles'              : 'CJ-迈尔斯',
    'Georges Niang'           : '乔治斯-尼昂',
    'Glenn Robinson III'      : '格伦-罗宾逊三世',
    'Kevin Seraphin'          : '凯文-塞拉芬',
    'Rodney Stuckey'          : '罗德尼-斯塔基',
    'Jeff Teague'             : '杰夫-蒂格',
    'Myles Turner'            : '迈勒斯-特纳',
    'Joe Young'               : '乔-杨',
    'Thaddeus Young'          : '赛迪斯-杨',

    # 费城76人
    'Jerryd Bayless'          : '杰里-贝勒斯',
    'Robert Covington'        : '罗伯特-卡温顿',
    'Joel Embiid'             : '乔尔-恩比德',
    'Gerald Henderson'        : '杰拉德-亨德森',
    'Richaun Holmes'          : '理查恩-霍姆斯',
    'Ersan Ilyasova'          : '艾森-伊利亚索瓦',
    'Timothe Luwawu-Cabarrot' : '蒂莫特-鲁瓦乌-卡巴洛特',
    'T.J. McConnell'          : 'T.J.迈克康内尔',
    'Nerlens Noel'            : '诺伦斯-诺尔',
    'Jahlil Okafor'           : '贾利尔-奥卡福',
    'Sergio Rodriguez'        : '塞尔吉奥-罗德里格兹',
    'Dario Saric'             : '达里奥-萨里奇',
    'Ben Simmons'             : '本-西蒙斯',
    'Nik Stauskas'            : '尼克-斯陶斯卡斯',
    'Hollis Thompson'         : '霍里斯-汤普森',

    # 奥兰多魔术
    'D.J. Augustin'           : 'D.J. 奥古斯汀, ',
    'Bismack Biyombo'         : '俾斯麦-毕永博',
    'Evan Fournier'           : '埃文-福尼尔',
    'Aaron Gordon'            : '阿隆-戈登',
    'Jeff Green'              : '杰夫-格林',
    'Mario Hezonja'           : '马里奥-赫佐尼亚',
    'Serge Ibaka'             : '赛尔吉-伊巴卡',
    'Jodie Meeks'             : '朱迪-米克斯',
    'Arinze Onuaku'           : '阿林泽-昂乌阿库',
    'Elfrid Payton'           : '艾弗里德-佩顿',
    'Damjan Rudez'            : '达米扬-鲁德兹',
    'Nikola Vucevic'          : '尼克拉-武切维奇',
    'C.J. Watson'             : 'C.J.-沃特森',
    'CJ Wilcox'               : 'CJ-威尔科斯',
    'Stephen Zimmerman'       : '斯蒂芬-齐默尔曼',

    # 波特兰开拓者
    'Al-Farouq Aminu'         : '艾尔-法鲁克-阿米奴',
    'Pat Connaughton'         : '帕特-康诺顿',
    'Allen Crabbe'            : '阿伦-克拉布',
    'Ed Davis'                : '艾德-戴维斯',
    'Festus Ezeli'            : '费斯图斯-艾泽里',
    'Maurice Harkles'         : '莫里斯-哈克里斯',
    'Jake Layman'             : '杰克-雷曼',
    'Meyers Leonard'          : '梅耶斯-伦纳德',
    'Damian Lillard'          : '达米安-利拉德',
    'C.J. McCollum'           : 'CJ-迈克勒姆',
    'Shabazz Napier'          : '沙巴兹-内皮尔',
    'Mason Plumlee'           : '梅森-普拉姆利',
    'Tim Quarterman'          : '蒂姆-夸特曼',
    'Evan Turner'             : '埃文-特纳',
    'Noah Vonleh'             : '诺阿-冯利',

    # 菲尼克斯太阳
    'Leandro Barbosa'         : '莱昂德罗-巴博萨',
    'Dragan Bender'           : '多拉甘-本德尔',
    'Eric Bledsoe'            : '埃里克-布莱索',
    'Devin Booker'            : '德文-布克',
    'Tyson Chandler'          : '泰森-钱德勒',
    'Marquese Chriss'         : '马奎斯-克里斯',
    'Jared Dudley'            : '贾里德-杜德利',
    'John Jenkins'            : '约翰-詹金斯',
    'Derrick Jones Jr.'       : '德里克-Jones, Jr.',
    'Brandon Knight'          : '布兰登-奈特',
    'Alex Len'                : '阿莱克斯-莱恩',
    'P.J. Tucker'             : 'PJ-塔克',
    'Tyler Ulis'              : '泰勒-尤利斯',
    'TJ Warren'               : 'TJ-沃伦',
    'Alan Williams'           : '阿兰-威廉姆斯',

    # 新奥尔良鹈鹕
    'Alexis Ajinca'           : '亚历克西斯-阿金萨',
    'Omer Asik'               : '欧米尔-阿西克',
    'Dante Cunningham'        : '丹特-康宁汉姆',
    'Anthony Davis'           : '安东尼-戴维斯',
    'Cheick Diallo'           : '谢赫-迪亚洛',
    'Tyreke Evans'            : '泰瑞克-埃文斯',
    'Tim Frazier'             : '蒂姆-弗雷泽尔',
    'Langston Galloway'       : '兰斯顿-格洛维',
    'Archie Goodwin'          : '阿尔奇-古德温',
    'Buddy Hield'             : '布迪-希尔德',
    'Solomon Hill'            : '所罗门-希尔',
    'Jrue Holiday'            : '朱-	霍利迪',
    'Terrence Jones'          : '特伦斯-琼斯',
    'E\'Twaun Moore'          : '伊托万-摩尔',
    'Quincy Pondexter'        : '昆西-庞德塞特',

    # 密尔沃基雄鹿
    'Giannis Antetokounmpo'   : '吉安尼斯-安特托昆博',
    'Michael Beasley'         : '迈克尔-比斯利',
    'Malcolm Brogdon'         : '马尔科姆-布罗格登',
    'Matthew Dellavedova'     : '马修-德拉维多瓦',
    'John Henson'             : '约翰-亨森',
    'Thon Maker'              : '索恩-马克',
    'Khris Middleton'         : '克里斯-米德尔顿',
    'Greg Monroe'             : '格雷格-门罗',
    'Steve Novak'             : '史蒂夫-诺瓦克',
    'Jabari Parker'           : '贾巴里-帕克',
    'Miles Plumlee'           : '米勒斯-普拉姆利',
    'Tony Snell'              : '托尼-斯内尔',
    'Mirza Teletovic'         : '米尔萨-泰勒托维奇',
    'Jason Terry'             : '贾森-特里',
    'Rashad Vaughn'           : '拉沙德-沃恩',

    # 多伦多猛龙
    'Bruno Caboclo'           : '布鲁诺-卡波科洛',
    'DeMarre Carroll'         : '德玛雷-卡罗尔',
    'DeMar DeRozan'           : '德玛尔-德罗赞',
    'Cory Joseph'             : '科里-约瑟夫',
    'Kyle Lowry'              : '凯尔-洛瑞',
    'Lucas Nogueira'          : '卢卡斯-诺盖拉',
    'Patrick Patterson'       : '帕特里克-帕特森',
    'Jakob Poeltl'            : '雅各布-珀尔特尔',
    'Norman Powell'           : '诺曼-鲍威尔',
    'Terrence Ross'           : '特伦斯-罗斯',
    'Pascal Siakam'           : '帕斯卡尔-西亚卡姆',
    'Jared Sullinger'         : '贾里德-萨林格',
    'Jonas Valanciunas'       : '乔纳斯-瓦兰西尤纳斯',
    'Fred VanVleet'           : '弗雷德-范弗里特',
    'Delon Wright'            : '德隆-怀特',

    # 华盛顿奇才
    'Bradley Beal'            : '布拉德利-比尔',
    'Trey Burke'              : '特雷-伯克',
    'Marcin Gortat'           : '马辛-戈塔特',
    'Danuel House'            : '丹尼尔-豪斯',
    'Ian Mahinmi'             : '伊安-马辛米',
    'Sheldon McClellan'       : '谢尔登-麦克莱伦',
    'Markieff Morris'         : '马基夫-莫里斯',
    'Andrew Nicholson'        : '安德鲁-尼克尔森',
    'Daniel Ochefu'           : '丹尼尔-奥彻夫',
    'Kelly Oubre Jr.'         : '凯利-小欧布雷',
    'Otto Porter Jr.'         : '奥托-小波特',
    'Tomas Satoransky'        : '托马斯-萨托兰斯基',
    'Jason Smith'             : '贾森-史密斯',
    'Marcus Thornton'         : '马库斯-索顿',
    'John Wall'               : '约翰-沃尔',

    # 犹他爵士
    'Joel Bolomboy'           : '乔尔-博罗姆博伊',
    'Alec Burks'              : '亚历克-伯克斯',
    'Boris Diaw'              : '鲍里斯-迪奥',
    'Dante Exum'              : '丹特-艾克萨姆',
    'Derrick Favors'          : '德里克-费沃斯',
    'Rudy Gobert'             : '鲁迪-戈波特',
    'Gordon Hayward'          : '戈登-海沃德',
    'George Hill'             : '乔治-希尔',
    'Rodney Hood'             : '罗德尼-胡德',
    'Joe Ingles'              : '乔-英格尔斯',
    'Joe Johnson'             : '乔-约翰逊',
    'Trey Lyles'              : '特雷-莱尔斯',
    'Shelvin Mack'            : '谢尔文-马克',
    'Raul Neto'               : '劳尔-内托',
    'Jeff Withey'             : '杰夫-威西',

    # 萨克拉门托国王
    'Arron Afflalo'           : '阿隆-阿夫拉罗',
    'Matt Barnes'             : '马特-巴恩斯',
    'Omri Casspi'             : '欧米-卡西比',
    'Willie Cauley-Stein'     : '威利-考利-斯坦',
    'Darren Collison'         : '达伦-科里森',
    'DeMarcus Cousins'        : '德玛库斯-考辛斯',
    'Rudy Gay'                : '鲁迪-盖伊',
    'Kosta Koufos'            : '科斯塔-库佛斯',
    'Skal Labissiere'         : '斯凯尔-拉比希埃',
    'Ty Lawson'               : '泰-劳森',
    'Ben McLemore'            : '本-麦克莱默',
    'Georgios Papagiannis'    : '乔吉奥斯-帕帕扬尼斯',
    'Malachi Richardson'      : '玛拉基-理查德森',
    'Garrett Temple'          : '加内特-坦普利',
    'Anthony Tolliver'        : '安东尼-特里沃',

    # 圣安东尼奥马刺
    'LaMarcus Aldridge'       : '拉马库斯-阿尔德里奇',
    'Kyle Anderson'           : '凯尔-安德森',
    'Davis Bertans'           : '戴维斯-贝尔坦斯',
    'Dewayne Dedmon'          : '德维恩-戴德蒙',
    'Bryn Forbes'             : '布林-福布斯',
    'Pau Gasol'               : '保罗-加索尔',
    'Manu Ginobili'           : '马努-吉诺比利',
    'Danny Green'             : '丹尼-格林',
    'Nicolas Laprovittola'    : '尼古拉斯-拉普罗维托拉',
    'David Lee'               : '尼古拉斯-拉普罗维托拉',
    'Kawhi Leonard'           : '科怀-伦纳德',
    'Patty Mills'             : '帕蒂-米尔斯',
    'Dejounte Murray'         : '德永特-穆雷',
    'Tony Parker'             : '托尼-帕克',
    'Jonathon Simmons'        : '乔纳森-西蒙斯',

    # 火箭
    'Ryan Anderson'           : '莱恩-安德森',
    'Trevor Ariza'            : '特雷沃-阿里扎',
    'Patrick Beverley'        : '帕特里克-贝弗利',
    'Corey Brewer'            : '科里-布鲁尔',
    'Bobby Brown'             : '鲍比-布朗',
    'Clint Capela'            : '克林特-卡佩拉',
    'Sam Dekker'              : '萨姆-德克尔',
    'Tyler Ennis'             : '泰勒-恩尼斯',
    'Eric Gordon'             : '埃里克-戈登',
    'James Harden'            : '詹姆斯-哈登',
    'Montrezl Harrell'        : '蒙特雷斯-哈雷尔',
    'Nene Hilario'            : '内内-希拉里奥',
    'K.J. McDaniels'          : '麦克丹尼尔斯',
    'Chinanu Onuaku'          : '奇拉鲁-昂乌阿库',
    'Kyle Wiltjer'            : '凯尔-维尔彻',

    # other
    'Jonathan Gibson'         : '乔纳森-吉布森',
    'jeol embiid'             : '乔尔-恩比德',
    'anthony brown': '安东尼布朗',
    'nene': '内内',
    'yogi ferrell': '费雷尔',
    'alonzo gee': '阿隆佐-基',
    'toney douglas': '托尼·道格拉斯',
    'Andy Greer': '安迪-格利尔',
    'reggie williams': '雷吉-威廉姆斯',
    'Rick Carlisle': '里克-卡莱尔',
    'pierre jackson': '皮雷-杰克逊',
    'David Nwaba': '大卫-恩瓦巴',
    'Shawn Long': '肖恩-朗',
    'Jordan Crawford': '乔丹-克劳福德',
    'Maurice Ndour': '莫里斯-恩多尔',
    'Joel Anthony': '乔尔-安东尼',
    'Okaro White': '奥卡罗-怀特',
    'TJ McConnell': 'T.J.麦康奈尔',
    'Norris Cole': '诺里斯-科尔',
    'Justin Harper': '贾斯汀-哈珀',
    'Donatas Motiejunas': '多纳塔斯-莫泰尤纳斯',
    'Briante Weber': '布莱恩蒂-韦伯',
    'Chasson Randle': '沙松-兰德尔',
    'Maurice Harkless': '莫里斯-哈克利斯',
    'Johnny O\'Bryant': '约翰尼-奥布莱恩特三世',
    'Quinn Cook': '奎因-库克',
    'Isaiah Taylor': '以赛亚-泰勒',
    'Lou Williams': '路易斯-威廉姆斯',
    'Ronnie Price': '罗尼-普莱斯',
    'Ben Bentil': '本-本蒂尔',
    'Spencer Dinwiddie': '斯宾瑟-丁维迪',
    'CJ McCollum': 'C.J.迈克勒姆',
    'Pj Tucker': 'P.J.塔克',
    'Dylan Ennis': '恩尼斯',
    'cliff alexander': '克里夫－亚历山大',
    'jarell eddie': '贾雷尔·埃迪',
    'ryan arcidiacono': 'ryan arcidiacono',
    'lauri markkanen': '劳里-马尔卡宁',
    'jalen jones': '杰伦－琼斯',
    'darius miller': '达柳斯·米勒',
    'jarrett jack': '贾瑞特·杰克',
    'jarrett allen': '贾莱特-阿伦',
    'jeremy senglin': '杰里米-森格林',
    'nigel hayes': 'nigel hayes',
    'damyean dotson': '丹伊恩·多特森',
    'de\'aaron fox': '德阿龙·福克斯',
    'bogdan bogdanovic': '博格丹·博格达诺维奇',
    'alex caruso': '亚历克斯·卡鲁索',
    'kyle kuzma': '凯尔·库兹马',
    'josh hart': '约什·哈特',
    'jakarr sampson': '贾卡尔·桑普森',
    'mario chalmers': '马里奥·钱莫斯',
    'tyler dorsey': '多西',
    'deandre\' bembry': "德安德鲁·本布里",

}

words = {
    r'(?:makes|made|make) (\d+)[ -]+foot +alley +oop +dunk +shot': '英尺空中接力灌篮成功',
    r'(?:misses|missed|miss) (\d+)[ -]+foot +alley +oop +dunk +shot': '英尺空中接力灌篮失败',
    r'(?:makes|made|make) +alley +oop +layup': '空中接力上篮命中',
    r'(?:misses|missed|miss) +alley +oop +layup': '空中接力上篮不中',
    r'taunting +technical *(?:foul)?': '恶意辱骂',
    r'(?:miss|misses|missed) +(\d+)[ -](?:ft|foot) +turnaround +fadeaway': '英尺翻身急停跳投不中',
    r'(?:make|makes|made) +(\d+)[ -](?:ft|foot) +turnaround +fadeaway': '英尺翻身急停跳投命中',
    r'illegal +screen +(?:turnover|violation)': '阻挡违例',
    r'double +technical +foul': '二次技术犯规',
    r'(?:miss|misses|missed) +jumper': '跳投不中',
    r'(?:make|makes|made) +jumper': '跳投命中',

    # pullup
    r'(?:make|made|makes) +(\d+)[ -](?:ft|foot) +(?:running)? +pullup +jump +shot': '英尺急停远跳投命中',
    r'(?:miss|missed|misses) +(\d+)[ -](?:ft|foot) +(?:running)? +pullup +jump +shot': '英尺急停远跳投不中',
    r'(?:make|made|makes) +(?:running)? +pullup +jump +shot': '英尺急停远跳投命中',
    r'(?:miss|missed|misses) +(?:running)? +pullup +jump +shot': '英尺急停远跳投不中',
    r'(?:make|made|makes) +(\d+)[ -](?:ft|foot) +pullup +jump +shot': '英尺急停跳投命中',
    r'(?:miss|missed|misses) +(\d+)[ -](?:ft|foot) +pullup +jump +shot': '英尺急停跳投不中',
    r'(?:miss|missed|misses) +pullup +jump +shot': '急停跳投命中',
    r'(?:make|made|makes) +three +point +pullup +jump +shot': '三分急停跳投命中',
    r'(?:miss|missed|misses) +three +point +pullup +jump +shot': '三分急停跳投不中',
    r'(?:make|made|makes) +two +point +pullup +jump +shot': '二分急停跳投命中',
    r'(?:miss|missed|misses) +two +point +pullup +jump +shot': '二分急停跳投不中',
    r'(?:make|made|makes) +(\d+)[ -](?:ft|foot) +three +point +pullup +jump +shot': '英尺三分急停跳投命中',
    r'(?:miss|missed|misses) +(\d+)[ -](?:ft|foot) +three +point +pullup +jump +shot': '英尺三分急停跳投不中',
    r'(?:miss|missed|misses) +(\d+)[ -](?:ft|foot) +two +point +pullup +jump +shot': '英尺二分急停跳投不中',
    r'(?:make|made|makes) +(\d+)[ -](?:ft|foot) +two +point +pullup +jump +shot': '英尺二分急停跳投命中',
    r'(?:make|made|makes) +shot': '投篮命中',
    r'(?:miss|missed|misses) +shot': '投篮不中',
    r'(?:make|made|makes) +(\d+)[ -](?:ft|foot) +shot': '英尺投篮命中',
    r'(?:miss|missed|misses) +(\d+)[ -](?:ft|foot) +shot': '英尺投篮不中',

    r'(?:misses|missed|miss) +(?:driving +)?floating +jump +shot': '漂移投篮不中',
    r'(?:makes|made|make) +(?:driving +)?floating +jump +shot': '漂移投篮命中',
    r'(?:misses|missed|miss) +(\d+)[ -](?:ft|foot) +(?:driving +)?floating +jump +shot': '英尺漂移投篮不中',
    r'(?:makes|made|make) +(\d+)[ -](?:ft|foot) +(?:driving +)?floating +jump +shot': '英尺漂移投篮命中',
    r'turnover *': '失误',
    r'no turnover': '无球失误',
    r'no foul': '无球犯规',
    r'no violation': '无球违例',

    r'palming +turnover': '翻腕失误',
    r'double +dribble +turnover': '两次运球失误',
    r'disc +dribble +turnover': '超时不运球失误',
    r'(?:misses|miss|missed) +alley +oop +dunk +shot': '第一时间灌篮失败',
    r'(?:makes|make|made) +alley +oop +dunk +shot': '第一时间灌篮成功',
    r'shot +clock +turnover': '进攻时间超时失误',
    r'in ?bound +foul': '边线球犯规',
    r'steps +out +of +bounds turnover': '踩线出界失误',
    r'\( *1st *': '(第一次',
    r'back court turnover': '回场失误',
    r'(?:make|makes|made) +regular +jump +shot': '常规跳投命中',
    r'(?:make|makes|made) +(\d+)[ -]+(?:ft|foot) +regular +jump +shot': '英尺常规跳投命中',
    r'(?:miss|misses|missed) +(\d+)[ -]+(?:ft|foot) +regular +jump +shot': '英尺常规跳投不中',
    r'(?:miss|misses|missed) +regular +jump +shot': '常规跳投不中',
    r'(\d+) +second(?:s)? +turnover': '秒失误',
    r'flagrant foul +type +2': '恶意犯规2',
    r'flagrant foul +type +1': '恶意犯规1',

    r'(?:miss|misses|missed) +(\d+)[ -]+(?:ft|foot) +putback +layup(?: +shot| *)'                                : '英尺补篮失败',
    r'(?:make|makes|made) +(\d+)[ -]+(?:ft|foot) +putback +layup(?: +shot| *)'                                   : '英尺补篮成功',
    r'(?:miss|misses|missed) +putback +layup(?: +shot| *)'                                : '补篮失败',
    r'(?:make|makes|made) +putback +layup(?: +shot| *)'                                   : '补篮成功',
    r'(?:misses|miss|missed) +tip[ -]*in': '补篮失败',
    r'(?:makes|make|made) +tip[ -]*in': '补篮成功',
    r'(?:misses|miss|missed) +(\d+)[ -]+(?:ft|foot) +tip[ -]*in': '英尺补篮失败',
    r'(?:makes|make|made) +(\d+)[ -]+(?:ft|foot) +tip[ -]*in': '英尺补篮成功',

    r'offensive +charge *'                                                        : '进攻时撞人',
    r'(?:make|makes|made) +(\d+)[- ]+(?:ft|foot) *$'                               : '英尺投篮命中',
    r'(?:miss|misses|missed) +(\d+)[- ]+(?:ft|foot) *$'                            : '英尺投篮不中',

    r'(?:make|makes|made) +finger +roll +lay *up'                                  : '低手上篮命中',
    r'(?:miss|misses|missed) +finger +roll +lay *up'                               : '低手上篮不中',

    r'(?:makes|made|make) *$'                                                      : '投篮命中',
    r'(?:misses|missed|miss) *$'                                                   : '投篮不中',
    r'(?:makes|made|make) +(\d+)[ -](?:ft|foot) +running +jumper'                          : '英尺远投命中',
    r'(?:misses|missed|miss) +(\d+)[ -](?:ft|foot) +running +jumper'                          : '英尺远投不中',
    r'(?:makes|made|make) +running +jumper'                          : '远投命中',
    r'(?:misses|missed|miss) +running +jumper'                          : '远投不中',
    r'(?:makes|made|make) +three +point(?:er)? +running +jumper'                          : '3分远投命中',
    r'(?:misses|missed|miss) +three +point(?:er)? +running +jumper'                       : '3分远投不中',
    r'(?:makes|made|make) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +running +jumper'   : '英尺3分远投命中',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +running +jumper': '英尺3分远投不中',
    r'(?:miss|misses|missed) +free +throw +clear +path'                            : '进攻犯规罚球不中',
    r'(?:make|makes|made) +free +throw +clear +path'                               : '进攻犯规罚球命中',
    r'clear +path +foul'                                                           : '进攻路径犯规',
    r'(?:make|makes|made) +(\d+)[- ]+(?:ft|foot) +jump +bank +shot'                : '英尺跳投擦板球命中',
    r'(?:miss|misses|missed) +(\d+)[- ]+(?:ft|foot) +jump +bank +shot'             : '英尺跳投擦板球命中',
    r'(?:make|makes|made) +jump +bank +shot'                                       : '跳投擦板球命中',
    r'(?:miss|misses|missed) +jump +bank +shot'                                    : '跳投擦板球不中',

    # 什么什么的
    r'\'s +(\d+)[ -]+(?:ft|foot) +driving +layup': '英尺的上篮',
    r'\'s +driving +layup': '的上篮',
    r'\'s +hook +shot': '的勾手投篮',
    r'\'s +(\d+)[ -]+(?:ft|foot) +hook +shot': '英尺的勾手投篮',
    r'\'s +shot'                                                                   : '的投篮',
    r'\'s +(\d+)[- ]+(?:ft|foot) +shot'                                            : '英尺投篮',
    r'shooting +block +foul'                                                       : '盖帽犯规',
    r'\'s +layup'                                                                  : '的上篮',
    r'\'s +(\d+)[- ]+(?:ft|foot) +layup'                                            : '英尺的上篮',
    r'\'s +(\d+)[- ]+(?:ft|foot) +jumper'                                           : '英尺的跳投',
    r'\'s +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +jumper'                                           : '英尺的三分跳投',
    r'\'s +three +point(?:er)? +jumper'                                           : '的三分跳投',
    r'\'s +(\d+)[- ]+(?:ft|foot) +two +point(?:er)? +jumper'                                           : '英尺的二分跳投',
    r'\'s +(\d+)[- ]+(?:ft|foot) +2-pt +jumper'                                           : '英尺的二分跳投',
    r'\'s +(\d+)[- ]+(?:ft|foot) +3-pt +jumper'                                           : '英尺的三分跳投',
    r'\'s +jumper'                                                                 : '的跳投',
    r'\'s +(\d+)[- ]+(?:ft|foot) +driving +floating +jump +shot': '英尺的漂移跳投',

    r'(?:misses|missed|miss) +step +back +jump *shot'                              : '后撤步跳投不中',
    r'(?:makes|made|make) +step +back +jump *shot'                                 : '后撤步跳投不中',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot) +step +back +jump *shot'       : '英尺后撤步跳投不中',
    r'(?:make|made|makes) +(\d+)[- ]+(?:ft|foot) +step +back +jump *shot'           : '英尺后撤步跳投命中',
    r'(?:makes|make|made) +dunk(?: *| *attempt *)'                                                   : '扣篮成功',
    r'(?:misses|miss|missed) +dunk(?: *| *attempt *)'                                                : '扣篮失败',
    r'(?:misses|miss|missed) +(\d+)[ -](?:ft|foot) +dunk(?: *| *attempt *)'                                                : '英尺扣篮失败',
    r'(?:makes|make|made) +(\d+)[ -](?:ft|foot) +dunk(?: *| *attempt *)'                                                : '英尺扣篮成功',
    r'assisted +by +([A-Za-z \'\.]+)'                                              : '助攻',
    r'stolen +by +([A-Za-z \'\.]+)'                                                : '助攻',
    r'blocked +by +([A-Za-z \']+)'                                                 : '盖帽',
    r'gains +possession'                                                           : '得到球',
    r'possession +lost +ball +turnover'                                            : '丢球失误',
    r'(?:miss|misses|missed) +(\d+)[ -]+(?:ft|foot) +layup'                                               : '英尺上篮不中',
    r'(?:miss|misses|missed) +layup'                                               : '上篮不中',
    r'(?:make|makes|made) +(\d+)[ -]+(?:ft|foot) +layup'                                                  : '英尺上篮命中',
    r'(?:make|makes|made) +layup'                                                  : '上篮命中',
    r'assists'                                                                     : '助攻',
    r'(?:makes|made|make) +driving +dunk'                                          : '突破扣篮得分',
    r'(?:misses|missed|miss) +driving +dunk'                                       : '突破扣篮失败',
    r'(?:misses|missed|miss) +(\d+)[ -]+(?:ft|foot) +driving +dunk'                                       : '英尺突破扣篮失败',
    r'(?:make|made|makes) +(\d+)[ -]+(?:ft|foot) +driving +dunk'                                       : '英尺突破扣篮成功',
    r'(?:makes|made|make) +driving +layup'                                         : '突破上篮得分',
    r'(?:misses|missed|miss) +driving +layup'                                      : '突破上篮失败',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot)\.? +hook +shot'                : '英尺勾手投篮不中',
    r'(?:makes|made|make) +(\d+)[- ]+(?:ft|foot)\.? +hook +shot'                   : '英尺勾手投篮命中',
    r'(?:misses|missed|miss) +hook +shot'                                          : '勾手投篮不中',
    r'(?:makes|made|make) +hook +shot'                                             : '勾手投篮不中',
    r'defensive +rebound'                                                          : '防守篮板',
    r'(?:missed|misses|miss) +(\d+)[- ]+foot +jump(?:er)?(?: *shot)?'                              : '英尺跳投不中',
    r'(?:made|makes|make) +(\d+)[- ]+foot +jump(?:er)?(?: *shot)?'                                 : '英尺跳投命中',
    r'(?:missed|misses|miss) +jump(?:er)?(?: *shot)'                                              : '跳投不中',
    r'(?:made|makes|make) +jump(?:er)?(?: *shot)'                                                 : '跳投命中',
    r'offensive +rebound'                                                          : '进攻篮板',
    r'(?:makes|made|make) +tip +shot'                                              : '补篮得分',
    r'(?:misses|missed|miss) +tip +shot'                                           : '补篮不中',
    r'out +of +bounds +lost +ball +turnover'                                       : '运球出界失误',

    r'(?:makes|made|make) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +shot'            : '英尺3分投篮命中',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +shot'         : '英尺3分投篮不中',
    r'(?:makes|made|make) +three +point(?:er)? +shot'                                   : '3分投篮命中',
    r'(?:misses|missed|miss) +three +point(?:er)? +shot'                                : '3分投篮不中',
    r'(?:makes|made|make) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)?(?: *$| +jumper)'            : '英尺3分投篮命中',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)?(?: *$| +jumper)'         : '英尺3分投篮不中',
    r'(?:makes|made|make) +three +point(?:er)?(?: *$| +jumper)'                                   : '3分投篮命中',
    r'(?:misses|missed|miss) +three +point(?:er)?(?: *$| +jumper)'                                : '3分投篮不中',
    r'(?:makes|made|make) +three +point(?:er)? +(?!jumper)'                                   : '3分投篮命中',
    r'(?:misses|missed|miss) +three +point(?:er)? +(?!jumper|pullup)'                                : '3分投篮不中',
    r'(?:makes|made|make) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +(?!jumper|running +jumper)'                                   : '英尺3分投篮命中',
    r'(?:misses|missed|miss) +(\d+)[- ]+(?:ft|foot) +three +point(?:er)? +(?!jumper|running +jumper)'                                : '英尺3分投篮不中',


    r'offensive +foul'                                                             : '进攻犯规',
    r'shooting +foul'                                                              : '投篮犯规',

    #罚球相关
    r'(?:misses|miss|missed) +technical +free +throw': '技术罚球不中',
    r'(?:makes|make|made) +technical +free +throw': '技术罚球命中',
    r'(?:make|makes|made) +free +throw +1 +of +1'                                  : '罚篮 第1罚（1罚）: 命中',
    r'(?:miss|misses|missed) +free +throw +1 +of +1'                               : '罚篮 第1罚（1罚）: 不中',
    r'(?:make|makes|made) +free +throw +1 +of +2'                                  : '罚篮 第1罚（2罚）: 命中',
    r'(?:miss|misses|missed) +free +throw +1 +of +2'                               : '罚篮 第1罚（2罚）: 不中',
    r'(?:make|makes|made) +free +throw +2 +of +2'                                  : '第2罚（2罚）: 命中',
    r'(?:miss|misses|missed) +free +throw +2 +of +2'                               : '第2罚（2罚）: 不中',
    r'(?:miss|misses|missed) +free +throw +2 +of +3'                               : '第2罚（3罚）: 不中',
    r'(?:miss|misses|missed) +free +throw +1 +of +3'                               : '第1罚（3罚）: 不中',
    r'(?:miss|misses|missed) +free +throw +3 +of +3'                               : '第3罚（3罚）: 不中',
    r'(?:make|makes|made) +free +throw +2 +of +3'                                  : '第2罚（3罚）: 命中',
    r'(?:make|makes|made) +free +throw +1 +of +3'                                  : '第1罚（3罚）: 命中',
    r'(?:make|makes|made) +free +throw +3 +of +3'                                  : '第3罚（3罚）: 命中',
    r'(?<!make|made|miss) +tip +layup'                                                                  : '点抢上篮',
    r'(?:misses|miss|missed) +tip +layup'                                                                  : '点抢上篮不中',
    r'(?:make|makes|made) +tip +layup'                                                                  : '点抢上篮命中',
    r'blocks'                                                                      : '封盖',
    r'offensive +team +rebound'                                                    : '全队进攻篮板',
    r'(?<!out-of-bounds) +bad +pass +turnover'                                     :'传球失误',
    r'(?<!out-of-bounds) +bad +pass *': '传球失误',
    r'out +of +bounds +bad +pass *': '踩线传球失误',
    r'steals'                                                                      : '抢断',
    r'full +timeout'                                                               : '长暂停',
    r'personal(?: +take)? +foul'                                                   : '个人犯规',
    r'personal +block +(?:foul)?'                                                  : '盖帽犯规',
    r'draws +the +foul'                                                            : '造成对手犯规',
    r'enters +the +game +for'                                                      : '上场替换',
    r'defensive +team +rebound'                                                    : '全队防守篮板',
    r'defensive +3[- ]+seconds'                                                    : '防守3秒',
    r'technical +foul'                                                             : '技术犯规',
    r'hanging +technical +foul': '把手挂在对方胳膊上',
    r'(?:make|makes|made) +technical +free +throw'                                 : '技术犯规罚篮命中',
    r'(?:made|make|makes) +two +point(?:er)? +(?:shot|jumper)'                            : '两分投篮命中',
    r'(?:miss|missed|misses) +two +point(?:er)? +(?:shot|jumper)'                         : '两分投篮不中',
    r'(?:made|make|makes) +(\d+)[- ]+(?:ft|foot) +two +point +(?:shot|jumper)'     : '英尺两分投篮命中',
    r'(?:miss|missed|misses) +(\d+)[- ]+(?:ft|foot) +two +point +(?:shot|jumper)'  : '英尺两分投篮不中',
    r'out-of-bounds +bad +pass +turnover'                                          : '传球出界失误',
    r'20 +sec\.? +timeout'                                                         : '短暂停',
    r'loose +ball +foul'                                                           : '无球犯规',
    r'Official +timeout'                                                           : '官方暂停',
    r'shot +clock +turnover '                                                      : '24秒进攻违例失误',
    r'defensive +goaltending +violation'                                           : '进攻干扰球违例',
    r'defensive +goaltending +turnover'                                           : '进攻干扰球失误',
    r'offensive +goaltending +turnover'                                           : '进攻干扰球失误',
    r'offensive +goaltending +violation'                                           : '进攻干扰球违例',
    r'offensive +goaltending *$'                                                   : '进攻干扰球',
    r'defensive +goaltending *$'                                                   : '防守干扰球',
    r'lane +violation'                                                             : '罚球违例',
    r'double +lane +violation'                                                     : '两次罚球违例',
    r'jump +ball +violation'                                                       : '跳球违例',

    r'kicked +ball +violation'                                                     : '脚踢球违例',
    r'kicked +ball +turnover'                                                     : '脚踢球失误',

    r'traveling'                                                                   : '走步',

    r'(?:five|5) +(?:sec|second|secs|seconds) +violation'                                                     : '五秒违例',
    r'(?:three|3) +(?:sec|second|secs|seconds) +violation'                                                    : '三秒违例',
    r'(?:5|five) +(?:sec|secs|second|seconds) +inbound +(?:turnover|violation)': '五秒边线球违例',
    r'(?:3|three) +(?:sec|secs|second|seconds) +inbound +(?:turnover|violation)': '三秒边线球违例',

    r'ejected'                                                                     : '被逐出场外',
    r'start of the 1st quarter'                                                    : '第一节开始',
    r'start of the 2nd quarter'                                                    : '第二节开始',
    r'start of the 3rd quarter'                                                    : '第三节开始',
    r'start of the 4th quarter'                                                    : '第四节开始',
    r'end of the 1st quarter'                                                      : '第一节结束',
    r'end of the 2nd quarter'                                                      : '第二节结束',
    r'end of the 3rd quarter'                                                      : '第三节结束',
    r'end of the 4th quarter'                                                      : '第四节结束',
    r'end of the 1st  overtime'                                                    : '第一节加时赛结束',
    r'end of the 2nd  overtime'                                                    : '第二节加时赛结束',
    r'end of the 3rt  overtime'                                                    : '第三节加时赛结束',
    r'end of the 4th  overtime'                                                    : '第四节加时赛结束',
    r'delay of game violation'                                                     : '阻碍比赛进行违例',
    r'too +many +players'                                                          : '队员太多',
    r'end +of +game'                                                               : '比赛结束',
    r'end +game'                                                                   : '比赛结束',
    r'start +of +the +1st quarter'                                                 : '第一节开始',
    r'(?:miss|missed|misses) +(\d+)[- ]+(?:ft|foot) +jumper'                       : '英尺跳投不中',
    r'(?:make|made|makes) +(\d+)[- ]+(?:ft|foot) +jumper'                          : '英尺跳投命中',
    r'jumpball'                                                                    : '跳球',
    r'(?<!out-of-bounds) +lost +ball +turnover *'                                                                  : '丢球失误',
    r'official +timeout'                                                           : '官方暂停',
}

nbateams = {
    'phoenix':'菲尼克斯水星',
    'phicago':'芝加哥天空',
    'washington':'华盛顿神秘人',
    'Atlanta Dream':'亚特兰大梦想',
    'atlanta':'亚特兰大梦想',
    'Dallas Wings':'达拉斯飞马',
    'dallas':'达拉斯飞马',
    # 'Chicago Sky':'芝加哥天空',
    'chicago':'芝加哥天空',
    'Las Vegas Aces':'拉斯维加斯王牌',
    'las vegas':'拉斯维加斯王牌',
    'Connecticut Sun':'康涅狄格太阳',
    'connecticut':'康涅狄格太阳',
    'Los Angeles':'洛杉矶火花',
    # 'los':'洛杉矶火花',
    'Indiana Fever':'印第安纳狂热',
    'indiana':'印第安纳狂热',
    'Minnesota':'明尼苏达山猫',
    'New York Liberty':'纽约自由人',
    'new york':'纽约自由人',
    'Phoenix Mercury':'菲尼克斯水星',
    'Washington Mystics':'华盛顿神秘人',
    'Seattle Storm':'西雅图风暴',
    'seattle':'西雅图风暴',
    'Charlotte Hornets'     : '黄蜂',
    'Boston Celtics'        : '凯尔特人',
    'Brooklyn Nets'         : '篮网',
    'New York Knicks'       : '尼克斯',
    'Philadelphia 76ers'    : '76人',
    'Toronto Raptors'       : '猛龙',
    'Chicago Bulls'         : '公牛',
    'Cleveland Cavaliers'   : '骑士',
    'Detroit Pistons'       : '活塞',
    'Indiana Pacers'        : '步行者',
    'Milwaukee Bucks'       : '雄鹿',
    'Atlanta Hawks'         : '老鹰',
    'Miami Heat'            : '热火',
    'Orlando Magic'         : '魔术',
    'Washington Wizards'    : '奇才',
    'Golden State Warriors' : '勇士',
    'LA Clippers'           : '快船',
    'Los Angeles Lakers'    : '湖人',
    'Phoenix Suns'          : '太阳',
    'Sacramento Kings'      : '国王',
    'Dallas Mavericks'      : '独行侠',
    'Houston Rockets'       : '火箭',
    'Memphis Grizzlies'     : '灰熊',
    'New Orleans Pelicans'  : '鹈鹕',
    'San Antonio Spurs'     : '马刺',
    'Denver Nuggets'        : '掘金',
    'Minnesota Timberwolves': '森林狼',
    'Oklahoma City Thunder' : '雷霆',
    'Portland Trail Blazers': '开拓者',
    'Utah Jazz'             : '爵士',
}


def translate(text):
    text = text.lower()
    for teamname_en, teamname_cn in sorted(nbateams.items(), reverse=True):
        teamname_en = teamname_en.lower()
        teamname_abbr = teamname_en.split()[-1]
        ind = text.find(teamname_abbr)
        if ind != -1:
            ind = len(teamname_abbr)+ ind
            text = text.replace(text[0:ind], teamname_cn)

    for name_en, name_cn in players.items():
        name_en = name_en.lower()
        if name_en in text:
            text = text.replace(name_en, name_cn)
    for word_en, word_cn in sorted(words.items(), key=lambda t: len(t[1]), reverse=True):
        # print word_en
        m = re.search(word_en, text)
        if m:
            try:
                num = m.group(1)
            except IndexError:
                word_en = m.group()
                text = text.replace(word_en, word_cn)
            else:
                word_en = m.group()
                text = text.replace(word_en, ''.join([num, word_cn]))
    return text.strip().replace('\t', '')


if __name__ == '__main__':
    print(translate('Minnesota 20 Sec. timeout'))
